-- MySQL Script generated by MySQL Workbench
-- Sat Feb 16 22:51:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema edumaster_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema edumaster_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edumaster_test` DEFAULT CHARACTER SET utf8 ;
USE `edumaster_test` ;

-- -----------------------------------------------------
-- Table `edumaster_test`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`course` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `courseName` VARCHAR(255) NOT NULL,
  `courseDescription` LONGTEXT NOT NULL,
  `courseImage` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`discipline` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `disciplineName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`course_discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`course_discipline` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `course_id` INT(11) NOT NULL,
  `discipline_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Curso_Disciplina_fk0` (`course_id` ASC) VISIBLE,
  INDEX `Curso_Disciplina_fk1` (`discipline_id` ASC) VISIBLE,
  CONSTRAINT `Curso_Disciplina_fk0`
    FOREIGN KEY (`course_id`)
    REFERENCES `edumaster_test`.`course` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `Curso_Disciplina_fk1`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `edumaster_test`.`discipline` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`institution` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `institutionName` VARCHAR(255) NOT NULL,
  `institutionStamp` VARCHAR(45) NOT NULL,
  `institutionCity` VARCHAR(255) NOT NULL,
  `institutionSales` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`institution_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`institution_course` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `institution_id` INT(11) NOT NULL,
  `course_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `Instituicao_Curso_fk0` (`institution_id` ASC) VISIBLE,
  INDEX `Instituicao_Curso_fk1` (`course_id` ASC) VISIBLE,
  CONSTRAINT `Instituicao_Curso_fk0`
    FOREIGN KEY (`institution_id`)
    REFERENCES `edumaster_test`.`institution` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `Instituicao_Curso_fk1`
    FOREIGN KEY (`course_id`)
    REFERENCES `edumaster_test`.`course` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`tuition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`tuition` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tuitionCode` VARCHAR(500) NOT NULL,
  `tuitionValue` INT(11) NOT NULL,
  `tuitionPaid` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`professor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `professorFName` VARCHAR(255) NOT NULL,
  `professorLName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`professor_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`professor_course` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `professor_id` INT(11) NOT NULL,
  `course_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_courseprofessor_id` (`course_id` ASC) VISIBLE,
  INDEX `fk_professorcourse_id` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_courseprofessor_id`
    FOREIGN KEY (`course_id`)
    REFERENCES `edumaster_test`.`course` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_professorcourse_id`
    FOREIGN KEY (`professor_id`)
    REFERENCES `edumaster_test`.`professor` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`professor_discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`professor_discipline` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `professor_id` INT(11) NOT NULL,
  `discipline_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_disciplineprofessor_id` (`discipline_id` ASC) VISIBLE,
  INDEX `fk_professordiscipline_id` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_disciplineprofessor_id`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `edumaster_test`.`discipline` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_professordiscipline_id`
    FOREIGN KEY (`professor_id`)
    REFERENCES `edumaster_test`.`professor` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`professor_institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`professor_institution` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `professor_id` INT(11) NOT NULL,
  `institution_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_institutionprofessor_id` (`institution_id` ASC) VISIBLE,
  INDEX `fk_professorinstitution_id` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_institutionprofessor_id`
    FOREIGN KEY (`institution_id`)
    REFERENCES `edumaster_test`.`institution` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_professorinstitution_id`
    FOREIGN KEY (`professor_id`)
    REFERENCES `edumaster_test`.`professor` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`student` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `studentFName` VARCHAR(255) NOT NULL,
  `studentLName` VARCHAR(255) NOT NULL,
  `studentEmail` VARCHAR(255) NOT NULL,
  `tuitionCode` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`student_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`student_course` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `course_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `curso_id` (`course_id` ASC) VISIBLE,
  INDEX `aluno_id` (`student_id` ASC) VISIBLE,
  CONSTRAINT `aluno_curso_ibfk_1`
    FOREIGN KEY (`course_id`)
    REFERENCES `edumaster_test`.`course` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `aluno_curso_ibfk_2`
    FOREIGN KEY (`student_id`)
    REFERENCES `edumaster_test`.`student` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`student_institution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`student_institution` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `student_id` INT(11) NOT NULL,
  `institution_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_studentinstitution_id` (`student_id` ASC) VISIBLE,
  INDEX `fk_institutionstudent_id` (`institution_id` ASC) VISIBLE,
  CONSTRAINT `fk_institutionstudent_id`
    FOREIGN KEY (`institution_id`)
    REFERENCES `edumaster_test`.`institution` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_studentinstitution_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `edumaster_test`.`student` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `edumaster_test`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edumaster_test`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `UserPassword` VARCHAR(45) NOT NULL,
  `UserImage` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
